CREATE TABLE user (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(60),
  email VARCHAR(255) UNIQUE,
  password TEXT,
  address VARCHAR(400),
  role VARCHAR(50) DEFAULT 'NORMAL',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE store (
  id VARCHAR(255) PRIMARY KEY,
  name TEXT,
  email TEXT,
  address TEXT,
  ownerId VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(ownerId) REFERENCES user(id)
);

CREATE TABLE rating (
  id VARCHAR(255) PRIMARY KEY,
  score INT,
  userId VARCHAR(255),
  storeId VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(userId, storeId),
  FOREIGN KEY(userId) REFERENCES user(id),
  FOREIGN KEY(storeId) REFERENCES store(id)
);